version: '3.0'
services:
  chatapp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379